"on":
    push:
        branches:
            - main
name: Deploy to uv-web-flask
jobs:
    porter-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set Github tag
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            - name: Setup porter
              uses: porter-dev/setup-porter@v0.1.0
            - name: Deploy stack
              timeout-minutes: 30
              run: porter apply
              env:
                PORTER_APP_NAME: uv-web-flask
                PORTER_CLUSTER: "1"
                PORTER_DEPLOYMENT_TARGET_ID: c418746c-3820-43f1-82e7-62747be551ef
                PORTER_HOST: https://gil.withporter.run
                PORTER_PROJECT: "1"
                PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
                PORTER_TOKEN: ${{ secrets.PORTER_APP_1_1084573258 }}
